import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseGoogleOAuth, oauthCredentials, microsoftClientId } from '../server/oauth-client.js';
import { bundleOAuth } from '../scripts/bundle-oauth.js';

test('desktop OAuth packaging validates credentials, strips unrelated data and requires explicit default selection', t => {
  const directory = mkdtempSync(join(tmpdir(), 'morrow-oauth-build-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const input = JSON.stringify({ installed: { client_id: 'fixture.apps.googleusercontent.com', client_secret: 'fixture-desktop-secret', project_id: 'unused', refresh_token: 'must-not-ship', auth_uri: 'https://untrusted.invalid' } });
  const credentials = parseGoogleOAuth(input);
  assert.equal(bundleOAuth(directory, { MORROW_GOOGLE_OAUTH_JSON: input }), true);
  const packaged = readFileSync(join(directory, 'google-oauth.json'), 'utf8');
  assert.deepEqual(parseGoogleOAuth(packaged), credentials);
  assert.deepEqual(Object.keys(JSON.parse(packaged).installed).sort(), ['client_id', 'client_secret']);
  assert.doesNotMatch(packaged, /must-not-ship|unused|untrusted/);
  assert.deepEqual(oauthCredentials('google', { useDefaultClient: true, organize: true }, credentials), { useDefaultClient: true, organize: true, ...credentials });
  assert.match(microsoftClientId, /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/);
  assert.deepEqual(oauthCredentials('microsoft', { useDefaultClient: true, organize: true }, credentials), { useDefaultClient: true, organize: true, clientId: microsoftClientId });
  const custom = { clientId: 'custom', clientSecret: 'custom-secret' };
  assert.equal(oauthCredentials('google', custom, credentials), custom);
  for (const [provider, body, client] of [['google', { useDefaultClient: true }, null], ['microsoft', { useDefaultClient: true, clientSecret: 'custom-secret' }, credentials], ['google', { useDefaultClient: true, clientId: 'custom' }, credentials], ['google', { useDefaultClient: true, clientSecret: 'custom-secret' }, credentials], ['google', { useDefaultClient: 'true' }, credentials]]) assert.throws(() => oauthCredentials(provider, body, client), { status: 400 });
  for (const invalid of ['{bad-json', 'null', JSON.stringify({ web: JSON.parse(input).installed }), JSON.stringify({ installed: { client_id: 'invalid', client_secret: 'sensitive-value' } }), JSON.stringify({ installed: { client_id: credentials.clientId, client_secret: 'secret\nvalue' } }), ' '.repeat(32769)]) assert.throws(() => parseGoogleOAuth(invalid), { message: 'Use a valid Google Desktop app OAuth JSON file.' });
  assert.throws(() => bundleOAuth(directory, { MORROW_REQUIRE_GOOGLE_OAUTH: '1' }), /requires a Google Desktop/);
  assert.throws(() => bundleOAuth(directory, { MORROW_GOOGLE_OAUTH_FILE: join(directory, 'missing.json') }), /Could not read/);
  assert.throws(() => bundleOAuth(directory, { MORROW_GOOGLE_OAUTH_FILE: 'file', MORROW_GOOGLE_OAUTH_JSON: input }), /Choose one/);
  assert.equal(bundleOAuth(directory, {}), false);
  assert.equal(existsSync(join(directory, 'google-oauth.json')), false);
});
